// API service for fetching data
// For GitHub Pages, you'll need to set up a serverless function or use direct DB queries
// This is a placeholder that can be adapted

const API_BASE_URL = process.env.REACT_APP_API_URL || 'http://localhost:8000'

export const getLatestBets = async () => {
  // Option 1: If using a serverless function (Vercel, Netlify, etc.)
  // const response = await fetch(`${API_BASE_URL}/api/bets`)
  // return response.json()
  
  // Option 2: For static site, use a JSON file that gets updated
  // This would be generated by GitHub Actions
  try {
    const response = await fetch('/NBABetv1/data/latest-bets.json')
    if (!response.ok) throw new Error('Failed to fetch')
    return response.json()
  } catch (error) {
    console.error('Error fetching bets:', error)
    // Return empty array or sample data
    return []
  }
}

export const reloadBets = async () => {
  // This would trigger a serverless function or webhook
  // that runs the main_workflow.py script
  try {
    const response = await fetch(`${API_BASE_URL}/api/reload`, {
      method: 'POST'
    })
    return response.json()
  } catch (error) {
    console.error('Error reloading bets:', error)
    throw error
  }
}

export const getPerformanceData = async () => {
  try {
    const response = await fetch('/NBABetv1/data/performance.json')
    if (!response.ok) throw new Error('Failed to fetch')
    return response.json()
  } catch (error) {
    console.error('Error fetching performance:', error)
    return null
  }
}
