// API service for fetching data
// For GitHub Pages, you'll need to set up a serverless function or use direct DB queries
// This is a placeholder that can be adapted

const API_BASE_URL = process.env.REACT_APP_API_URL || 'http://localhost:8000'

export const getLatestBets = async () => {
  // Option 1: If using a serverless function (Vercel, Netlify, etc.)
  // const response = await fetch(`${API_BASE_URL}/api/bets`)
  // return response.json()
  
  // Option 2: For static site, use a JSON file that gets updated
  // This would be generated by GitHub Actions
  try {
    // Try with timestamp to avoid caching issues
    const url = '/NBABetv1/data/latest-bets.json?' + new Date().getTime()
    const response = await fetch(url, {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
      },
      cache: 'no-cache'
    })
    
    if (!response.ok) {
      console.warn(`Failed to fetch bets: ${response.status} ${response.statusText}`)
      return []
    }
    
    const data = await response.json()
    
    // Validate that we got an array
    if (!Array.isArray(data)) {
      console.warn('Invalid data format: expected array, got:', typeof data)
      return []
    }
    
    return data
  } catch (error) {
    console.error('Error fetching bets:', error)
    // Return empty array on error
    return []
  }
}

export const reloadBets = async () => {
  // This would trigger a serverless function or webhook
  // that runs the main_workflow.py script
  try {
    const response = await fetch(`${API_BASE_URL}/api/reload`, {
      method: 'POST'
    })
    return response.json()
  } catch (error) {
    console.error('Error reloading bets:', error)
    throw error
  }
}

export const getPerformanceData = async () => {
  try {
    const response = await fetch('/NBABetv1/data/performance.json')
    if (!response.ok) {
      // Return empty structure if file doesn't exist or fails to load
      return {
        totalBets: 0,
        wins: 0,
        losses: 0,
        winRate: 0,
        totalProfit: 0,
        roi: 0,
        byProp: [],
        overTime: []
      }
    }
    const data = await response.json()
    // Ensure we always return a valid structure
    return data || {
      totalBets: 0,
      wins: 0,
      losses: 0,
      winRate: 0,
      totalProfit: 0,
      roi: 0,
      byProp: [],
      overTime: []
    }
  } catch (error) {
    console.error('Error fetching performance:', error)
    // Return empty structure instead of null
    return {
      totalBets: 0,
      wins: 0,
      losses: 0,
      winRate: 0,
      totalProfit: 0,
      roi: 0,
      byProp: [],
      overTime: []
    }
  }
}
